config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :registrations }
#   as :user do
#   get 'users', :to => 'users#show', :as => :user_root # Rails 3
# end


  # 管理员路由
  namespace :admin do
    resources :questions do
      resources :answers
    end
    resources :documents
     resources :feedbacks
     resources :orders
    resources :conversations
    resources :users do
      member do
        post :change_to_user
        post :change_to_lawyer
        post :change_to_vip
        post :change_to_visitor
      end
    end
  end

  # 普通用户路由
  namespace :account do
    resources :documents
    resources :feedbacks

    #order路由
    resources :orders do
      collection do
        post :create_m
        post :create_y
      end
      #支付路由
      member do
        post :pay_with_alipay
        post :pay_with_wechat
      end
    end

    resources :users
    resources :questions do
      resources :answers
      resources :conversations do
        member  do
          get :show_lawyer
         end
      end

      # 评价系统
      collection do
        post :rating
        get  :new_document
      end

    end

  end

  # 律师路由
  namespace :lawyer do
    resources :users
    resources :questions do
      resources :answers
    end
    resources :documents do
      resources :feedbacks
    end

  end

  # f783-站内通知
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end


  resources :welcome do

    collection do
      # post :pricing  #支付路由
      # 获取路人问题
      post :get_temp_question
    end

  end

  get "/price", to: "welcome#price"
  get "/about_us", to: "welcome#about_us"
  get "/help_term", to: "welcome#help_term"
  get "/contact_us", to: "welcome#contact_us"
  get "/sec_price", to: "welcome#sec_price"


  root 'welcome#index'

end

app/models/lawyer.rb
class Lawyer < ApplicationRecord
  belongs_to :user

  # 律师与问题的多对多关系
  has_many :lawyer_answered_questions
  # has_and_belongs_to_many :questions

end

# == Schema Information
#
# Table name: lawyers
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/controllers/account/users_controller.rb
class Account::UsersController < AccountController
  before_action :find_current_user,only: [:index, :edit, :show]

  def index
  end


  def edit
    @user = User.find(params[:id])
  end


  def show
  end


  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to account_users_path
    else
      render :edit
    end
  end

  private

  def find_current_user
     @user = current_user
   end

  def user_params
    params.require(:user).permit(:user_name,:email,:user_avatar,:district,:area,:certificate, :certificate_number)
  end

end

app/controllers/admin/lawyers_controller.rb
class Admin::LawyersController < ApplicationController
  before_action :lawyer_required
  before_action :authenticate_user!

  layout "lawyer"

  # 只显示当前用户的问题
  def index
    @questions = Question.all
  end

  # 查看问题
  def show
    @question = Question.find(params[:id])
    @answers = @question.answers
    @new_answer = Answer.new
  end

# 回答问题
  def create
    @question = Question.find(params[:question_id])
    @new_answer = Answer.new(answer_params)
    @new_answer.user = current_user
    @new_answer.question = @question
    if @new_answer.save
      flash[:notice] = "回答成功！"
      redirect_to :back
    else
      flash[:alert] = "修改失败!"
      redirect_to :back
    end
  end

  # 更新回答
  def update
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
    if @answer.update(answer_params)
      redirect_to admin_question_path(@question), notice: "答案修改成功!"
    else
      render :back, notice: "答案修改失败!"
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:content)
  end



  # 增加需要律师登录
  def lawyer_required
    if !current_user.lawyer?
      redirect_to '/'
    end
  end
end

app/controllers/admin/user_controller.rb
class Admin::UserController < ApplicationController
  before_action :authenticate_user!,only:[:new,:create,:update,:edit]
  before_action :lawyer_required
  before_action :require_is_admin
def index
@users = User.all
# @user =Usesr.new
end

def new
@user = User.new
end

def show
@user = User.find(params[:id])
end

def create
@user = User.new(user_params)
if @user.save
redirect_to :back
else
render :new
end
end

def edit
@user = User.find(params[:id])
end

def update
@user = User.find(params[:id])
if @user.update(user_params)
redirect_to :back
else
render :edit
end
end

private

def user_params
params.require(:user).permit(:district,:area,:is_admin,:is_lawyer,:id,:email,:encrypted_password,:reset_password_token,:reset_password_sent_at,:remember_created_at,:sign_in_count,:current_sign_in_at,:last_sign_in_at,:current_sign_in_ip,:last_sign_in_ip,:created_at,:updated_at)
end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController

  def index
    @users =  case params[:order]
    when 'by_lawyer'
      User.lawyer
    when 'by_account'
      User.account
    else
      User.all.recent
    end
  end

  def show
    @user = User.find(params[:id])
  end


  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:alert]="User deleted."
    redirect_to :back
  end

  def change_to_user
    @user = User.find(params[:id])
    @user.is_lawyer= false
    @user.save

    redirect_to :back
  end

  def change_to_lawyer
    @user = User.find(params[:id])
    @user.is_lawyer= true
    @user.save
    # f1195-fixLawyerQuestionSystem
    @user.is_lawyer!
    #
    redirect_to :back
  end

  def change_to_vip
    @user = User.find(params[:id])
    @user.is_vip = true
    @user.save

    redirect_to :back
  end

  def change_to_visitor
    @user = User.find(params[:id])
    @user.is_vip = false
    @user.save

    redirect_to :back
  end



end

app/controllers/lawyer/answers_controller.rb
class Lawyer::AnswersController < LawyerController


  # 回答问题
  def create
    @question = Question.find(params[:question_id])
    # 出题人
    akser = @question.user
    # 问题内容和问题id绑定
    subject = @question.content
    # 回答内容
    answer_content = answer_params[:content]
    # 获取附件
    attachment = answer_params[:attachment]
    # 对话id
    conversation_id = answer_params[:conversation_id]

    # mailboxer方法
    # 如果之前没有对话，就新建对话。如果有，就回复对话
    if conversation_id.blank?
      # 使用修正过得新send_message多加了一个参数
      conversation = current_user.send_message(akser ,answer_content ,subject , @question,true,attachment).conversation
      # 发送给用户回答问题的提醒
      send_notification!(akser.id, current_user.id, @question)
    else
      # 通过会话id获取会话
      conversation = @question.conversations.find(conversation_id)
      # binding.pry
      current_user.reply_to_conversation(conversation, answer_content,nil,true,true,attachment)
      # 发送给用户回答问题的提醒
      send_notification!(akser.id, current_user.id, @question)
    end
    # 更新律师与问题的多对多回答表
    lawyer_answer_question = LawyerAnsweredQuestion.new
    lawyer_answer_question.lawyer = current_user.lawyer
    lawyer_answer_question.question = @question
    lawyer_answer_question.save
    #

    # f470-变成已回答状态
    @question.answered!

    flash[:notice] = "回复成功"
    redirect_to :back
  end

  private

  def answer_params
    params.require(:answer).permit(:content,:conversation_id,:attachment)
  end

end

app/controllers/lawyer/questions_controller.rb
class Lawyer::QuestionsController < LawyerController


    def index
      @user = current_user
      @questions = case params[:order]
        #全部问题按照领域排序

        # when 'by_area'
        #   Question.area
        #   #全部问题按照地域排序
        # when 'by_district'
        #   Question.district
        #   #仅显示登陆的律师所在领域的问题
        # when 'lawyer_area'
        #   my_area = @user.area
        #   Question.where(area:my_area)
        #   #仅显示登陆的律师所在地区的问题
        # when 'lawyer_district'
        #   my_district = @user.district
        #   Question.where(district:my_district)
        # #仅显示登陆的律师所在地区及领域的问题并显示最新时间排序
        # when 'lawyer_two'
        #   my_district = @user.district
        #   my_area = @user.area
        #   Question.where(district:my_district,area:my_area).recent
        # f1195-fixLawyerQuestionSystem
        # 可回答问题
        when 'waiting_for_answer'
          # my_district = @user.district
          # my_area = @user.area
          fliter_questions = Question.all
          waiting_questions =  fliter_questions - current_user.answered_questions
          # puts waiting_questions
          # 数组按时间倒序排列
          waiting_questions.sort_by{ |i| i.created_at }.reverse
        # 答过的问题
        when 'already_answered'
          # 数组按时间倒序排列
          current_user.answered_questions.sort_by{ |i| i.created_at }.reverse
        #
        else
          #所有问题按照最新时间排序
          Question.recent
        end

    end


    #查看问题
    def show
      @question = Question.find(params[:id])
      @answers = @question.answers
      @new_answer = Answer.new

      # f120

      # 查是否有关于此问题的回复
      dialog = @mailbox.conversations.find_by(question_id: @question)

      # binding.pry
      if dialog.present?
        # 如果有就交给@message
        # 生产异常message序列，使用逆序
        @messages = dialog.messages.order(created_at: :ASC)

        # binding.pry
        @conversation = dialog
      end

    end




end

app/controllers/lawyer/users_controller.rb
class Lawyer::UsersController < LawyerController
 

  def index
    @user = current_user
    @lawyer_rating = average_rating(current_user)
  end


  def edit
    @user = current_user
    @user = User.find(params[:id])
  end


  def show
    @user = current_user

  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to lawyer_users_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:user_name,:email,:user_avatar,:district,:area,:lawfirm,:certificate,:certificate_number)
  end

end

app/controllers/lawyer_controller.rb
class LawyerController < ApplicationController
    before_action :authenticate_user!
    before_action :lawyer_required
    before_action :get_mailbox
    layout "lawyer"


end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!,only:[:new,:create,:update,:edit]

def new
@user = User.new
end

def show
@user = User.find(params[:id])
end

def create
@user = User.new(user_params)
if @user.save
redirect_to :back
else
render :new
end
end

def edit
@user = User.find(params[:id])
end

def update
@user = User.find(params[:id])
if @user.update(user_params)
redirect_to :back
else
render :edit
end
end

private

def user_params
  params.require(:user).permit(:district,:area,:is_admin,:is_lawyer,:id,:email,:encrypted_password,:reset_password_token,:reset_password_sent_at,:remember_created_at,:sign_in_count,:current_sign_in_at,:last_sign_in_at,:current_sign_in_ip,:last_sign_in_ip,:created_at,:updated_at)
end
end

app/helpers/account/users_helper.rb
module Account::UsersHelper
  def render_user_vip(user)
    if !user.is_vip?
      content_tag(:span,"", class:"fa fa-opera")
    else
      content_tag(:span,"", class:"fa fa-vimeo")
    end

  end
end

app/helpers/admin/lawyers_helper.rb
module Admin::LawyersHelper
end

app/helpers/admin/user_helper.rb
module Admin::UserHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper

  def render_user_avatar(user)
    if !user.user_avatar.present?
      image_tag user.gravatar_url
    else
      image_tag (user.user_avatar.url(:middle))
    end
  end




  def render_user_small_avatar(user)
    if !user.user_avatar.present?
    image_tag user.gravatar_url,class:"lawyerImage"
  else
    image_tag (user.user_avatar.url(:small)),class:"lawyerImage"
  end
end

  def change_user_status(user)
    if !user.is_lawyer?
      link_to("设为律师", change_to_lawyer_admin_user_path(user), method: :post,data: { confirm: "确认认证为律师么？" }, class:"btn btn-xs btn-danger")
    else
      link_to("设为用户", change_to_user_admin_user_path(user), method: :post,data: { confirm: "确认降级为顾客么？" }, class:"btn btn-xs btn-warning")
    end
  end


  #认证律师
  def change_lawyer_status(user)
    if  !user.is_lawyer? && user.role == "律师"
      link_to("设为律师", change_to_lawyer_admin_user_path(user), method: :post,data: { confirm: "确认认证为律师么？" }, class:"btn btn-xs btn-danger")
    else user.is_lawyer && user.role == "用户"
      link_to("设为用户", change_to_user_admin_user_path(user), method: :post,data: { confirm: "确认降级为顾客么？" }, class:"btn btn-xs btn-warning")
    end
end
  def chenge_user_vip(user)
    if !user.is_vip?
      link_to("设为VIP", change_to_vip_admin_user_path(user), method: :post,data: {confirm: "确认认证VIP？"}, class: "btn btn-xs btn-warning")
    else
      link_to("取消VIP", change_to_visitor_admin_user_path(user), method: :post, data: {confirm: "取消认证VIP？"}, class: "btn btn-xs btn-warning ")
    end
  end

  def render_user_status(user)
    if !user.is_admin?
      if user.is_lawyer?
        content_tag(:span,"",class:"fa fa-user-plus")
      else
        content_tag(:span, "", class: "fa fa-user")
      end
    else
      content_tag(:span,"",class:"fa fa-star-o")
    end
  end


  def render_user_vip(user)
    if !user.is_vip?
      content_tag(:span,"", class:"fa fa-opera")
    else
      content_tag(:span,"", class:"fa fa-vimeo")
    end

  end


end

app/helpers/lawyer/answers_helper.rb
module Lawyer::AnswersHelper
end

app/helpers/lawyer/question_helper.rb
module Lawyer::QuestionHelper
end

app/helpers/lawyer/questions_helper.rb
module Lawyer::QuestionsHelper
end

app/helpers/lawyer/users_helper.rb
module Lawyer::UsersHelper
end

app/helpers/lawyer_helper.rb
module LawyerHelper
end

app/views/lawyer/users/edit.html.erb
  <div class="container-fluid well">




<div class="user-center-detail-block">
<h4> 修改个人资料 </h4>
<%= simple_form_for [:lawyer,@user] do |f| %>

<div>
<%= f.input :user_avatar,label:"上传头像" %>
 <%=f.input :user_name, label:"用户名" %>
<%= f.input :email ,label:"邮箱"%>
<%= f.input :district, label:"地区"%>

<%= f.input :area, label:"领域" %>
<%= f.input :lawfirm, label:"律师事务所" %>
<%= f.input :certificate_number, label: "律师证号" %>
<%= f.input :certificate,label: "上传律师资格证"%>

<%= f.submit "提交", class: "btn  btn-secondary text-uppercase flat animation" %>
</div>
<% end %>
</div>
</div>
</div>

app/views/lawyer/users/index.html.erb
<div class="container-fluid well">

    <div class="col-md-2">
        <% if !@user.user_avatar.present? %>
        <%= image_tag "http://placehold.it/150x150" %>
    <% else %>
        <%= image_tag (@user.user_avatar.url(:middle)) %>
        <% end %>

    </div>
    <div class="col-md-8 col-md-offset-1">
        <table class="table user-table-info">
            <tbody>
              <tr>
                <h6>我的资料</h6>

              </tr>

                <tr>
                    <td>用户名</td>
                  <td>  <%= render :partial => "common/user_name", :locals =>{:user => @user} %></td>

                </tr>


                <tr>
                    <td>好评</td>
                    <td><div id="average_rating"></div></td>
                </tr>

                <tr>
                    <td>电子邮件</td>
                    <td><%= @user.email %></td>
                </tr>
                <tr>
                    <td>所在地区</td>
                    <td><%= @user.district %></td>
                </tr>

                <tr>
                    <td>领域</td>
                    <td><%= @user.area %></td>
                </tr>
                <tr>
                    <td>律师事务所</td>
                    <td><%= @user.lawfirm %></td>
                </tr>
                <tr>
                    <td>律师证号</td>
                    <td><%= @user.certificate_number %></td>
                </tr>
                <td>律师证</td>
                <td>

                    <% if !@user.certificate.present? %>
                    <%= image_tag "http://placehold.it/150x150" %>
                <% else %>
                    <%= image_tag(@user.certificate.preview.url) %>
                    <% end %>
                </td>

            </tbody>
        </table>


    <div>
      <%= link_to("完善个人资料", edit_lawyer_user_path(@user), :class => "btn  btn-secondary text-uppercase flat animation") %>
      <%= link_to("修改密码", edit_user_registration_path, class: "btn  btn-secondary text-uppercase flat animation" ) %>

          </div>
        </div>
        </div>
    </div>
  </div>
</div>



 <!-- 星星评级  -->
<script>

$(function() {

  // 锁定部分样式
  $('#average_rating').raty({
    // 设置rating路径
    path:"https://ooo.0o0.ooo/2016/11/30/",
    starOff: '583e808d20d1d.png',
    starHalf: '583e808cebb65.png',
    starOn: '583e808cdddbe.png',
    size: 32,
    readOnly: true, 
    score: '<%= @lawyer_rating %>',
    round: { down: .25, full: .6, up: .76 } 
  });

    
});


</script>

app/views/lawyer/users/new.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>申请成为本站律师</h2>

    <hr>
<%= simple_form_for  [:lawyer, @user] do |l| %>

<div class="form-group">
    <%= l.input :area, label: '案件类型',collection: [["民事", "民事"],["刑事", "刑事"],["商业", "商业"],["行政", "行政"]],:selected => "民事" %>
    <%= l.input :district, label: '地区',collection: [["北京", "北京"], ["上海", "上海"],["广州", "广州"],["深圳", "深圳"]],:selected => "北京" %>
    <%= l.input :content, label: '问题描述',input_html: { class: "form-control"} %>


</div>
<%= l.submit "提交", class: "btn  btn-secondary text-uppercase flat animation", data: { disable_with: "提交..." } %>
<% end %>
</div>

app/views/lawyer/users/show.html.erb
<h2>个人信息</h2>
<table class="table table-boldered">
    <tr>
        <th>用户名</th>
        <th>好评</th>
        <th>用户邮箱</th>

        <th>律师事务所</th>
        <th>领域</th>
        <th>城市</th>
        <th>律师证号</th>

    </tr>
    <tr>
      <%= render :partial => "common/user_name", :locals =>{:user => @user} %>

        <td><div id="average_rating"></div></td>
        <td><%= @user.email %></td>
        <td><%= @user.lawfirm %></td>
        <td><%= @user.area %></td>
        <td><%= @user.district %></td>
        <td><%= @user.certificate_number %></td>

    </tr>
</table>

 <!-- 星星评级  -->
<script>

$(function() {

  // 锁定部分样式
  $('#average_rating').raty({
    // 设置rating路径
    path:"https://ooo.0o0.ooo/2016/11/30/",
    starOff: '583e808d20d1d.png',
    starHalf: '583e808cebb65.png',
    starOn: '583e808cdddbe.png',
    size: 32,
    readOnly: true, 
    score: <%= @lawyer_rating %>,
    round: { down: .25, full: .6, up: .76 } 
  });

    
});


</script>