config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :registrations }
#   as :user do
#   get 'users', :to => 'users#show', :as => :user_root # Rails 3
# end


  # 管理员路由
  namespace :admin do
    resources :questions do
      resources :answers
    end
    resources :documents
     resources :feedbacks
     resources :orders
    resources :conversations
    resources :users do
      member do
        post :change_to_user
        post :change_to_lawyer
        post :change_to_vip
        post :change_to_visitor
      end
    end
  end

  # 普通用户路由
  namespace :account do
    resources :documents
    resources :feedbacks

    #order路由
    resources :orders do
      collection do
        post :create_m
        post :create_y
      end
      #支付路由
      member do
        post :pay_with_alipay
        post :pay_with_wechat
      end
    end

    resources :users
    resources :questions do
      resources :answers
      resources :conversations do
        member  do
          get :show_lawyer
         end
      end

      # 评价系统
      collection do
        post :rating
        get  :new_document
      end

    end

  end

  # 律师路由
  namespace :lawyer do
    resources :users
    resources :questions do
      resources :answers
    end
    resources :documents do
      resources :feedbacks
    end

  end

  # f783-站内通知
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end


  resources :welcome do

    collection do
      # post :pricing  #支付路由
      # 获取路人问题
      post :get_temp_question
    end

  end

  get "/price", to: "welcome#price"
  get "/about_us", to: "welcome#about_us"
  get "/help_term", to: "welcome#help_term"
  get "/contact_us", to: "welcome#contact_us"
  get "/sec_price", to: "welcome#sec_price"


  root 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    # flash[:notice] = "早安！你好！"
    # 给个可以发临时问题的页面，可以接收问题和用户邮箱
    @temp_question = TempQuestion.new
    # binding.pry
  end

  def price
  end
  def about_us
  end
  def help_term
  end
  def contact_us
  end
  def sec_price
  end 


  # 获取路人问题
  def get_temp_question
    # 接收用户的问题
    temp_queston = TempQuestion.create(temp_question_params)
    new_user_email = temp_question_params[:email]
    new_quesion_content = temp_question_params[:content]

    # hash用户的密码
    generated_password = Devise.friendly_token.first(8)

    # 看这个用户是否之前建立过
    user = User.find_by(email: new_user_email)
    if user.blank?
      # 建立新用户
      user =  User.create(:email => new_user_email, :password => generated_password)
      # binding.pry
      # send_password_mail(user.id,generated_password)

      # 验证devise是否成功建立用户
      if user.id.blank?
        flash[:notice] = "注册信息有误，提问失败，请输入有效邮箱注册！"
        redirect_to new_user_session_path
      else

        # 只有生产环境才发邮件
        if Rails.env == 'production'
          # 延迟发送邮件
          ModelMailer.send_password_mail(user.id,generated_password).deliver_later          
        end

        # 为这个用户建立新问题
        question = Question.create(content: new_quesion_content, user: user)
        flash[:notice] = "默认密码已经发送到您的邮箱，请查收！"

        # 用户登录
        sign_in user
        # 用户重定向
        redirect_to account_questions_path

      end


    else
      # 如果是已存在用户让他登录
      redirect_to new_user_session_path
    end

  end


  private

  # 接收用户的临时问题
  def temp_question_params
    params.require(:temp_question).permit(:email,:content)
  end

 def join_us

 end

 def abouts

 end

 def map_guides
 end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<!-- Slider Starts -->



  <div id="main-slider" class="carousel slide" data-ride="carousel">
  <!-- Wrapper For Slides Starts -->
    <div class="carousel-inner text-center">
    <!-- Slide #1 Starts -->
      <div class="item active">
        <%= image_tag "http://ohjgz7qhu.bkt.clouddn.com/slider-img2-3f88c49b1a145ef798f5eeb7cf16cb110c9fc7f14aec61b122686f8e3ad714e1.jpg", class:"img-responsive" %>

        <div class="carousel-caption hidden-xs text-right">
          <h2 class="text-thin">终身伴律</h2>
          <h1 class="text-light">为你摆平一切</h1>
          <p>让顶级律师成为你随身的法律顾问 <br>从此法律零门槛 </p>

         <%= link_to "立即咨询", "#heading-block",class:"btn btn-secondary animation text-uppercase flat"%>
        </div>
        <div class="carousel-caption text-left-xs hidden-sm hidden-md hidden-lg">
          <h2 class="text-light">终身伴律</h2>
         <%= link_to "立即向律师提问", "#heading-block",class:"btn btn-secondary animation  flat"%>
         </div>
      </div>
    <!-- Slide #1 Ends -->
    <!-- Slide #2 Starts -->
      <div class="item">
        <%= image_tag "http://ohjgz7qhu.bkt.clouddn.com/slider-img1-5a2374d0e41087e13b30df4fbd265c86822868163e1494de067b1dc9717db1eb.jpg", class:"img-responsive" %>

        <div class="carousel-caption hidden-xs text-right">
          <h2 class="text-center">终身伴律</h2>

          <h1 class="text-light">你的随身法律顾问</h1>
          <p>为你解决一切法律难题<br>告别晦涩难懂</p>

          <!-- <a href="#" class="btn btn-secondary animation text-uppercase flat">立即咨询</a> -->
          <%= link_to "立即咨询", "#heading-block",class:"btn btn-secondary animation text-uppercase flat"%>
        </div>
        <div class="carousel-caption text-left-xs hidden-sm hidden-md hidden-lg">
          <h2 class="text-light">终身伴律</h2>
         <%= link_to "立即向律师提问", "#heading-block",class:"btn btn-secondary animation text-uppercase flat"%>
         </div>
      </div>
    <!-- Slide #2 Ends -->
    </div>
  <!-- Wrapper For Slides Ends -->
  <!-- Controls Starts -->
    <a class="left carousel-control" href="#main-slider" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#main-slider" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  <!-- Controls Ends -->
  </div>
<!-- Slider Ends -->
<!-- Intro Section Starts -->
  <section class="intro-home-section">
  <!-- Nested Container Starts -->
    <div class="container-fluid">
    <!-- Nested Row Starts -->
      <div class="row-fluid row-eq-height">
      <!-- Left Col Starts -->
        <div class="col-lg-6 col-md-6 col-xs-12">
          <div class="row">
            <div class="col-xs-10 col-xs-offset-1 text-center">
              <h4 class="text-uppercase">在线咨询法律问题</h4>
              <p>资深法律专家就在你身边，满足您任何时间任何地点任何不解、疑惑</p>
              <p>直接发问，上千律师在线等。</p>
            </div>
          </div>
        </div>
      <!-- Left Col Ends -->
      <!-- Right Col Starts -->
        <div class="col-lg-6 col-md-6 col-xs-12">
          <div class="row">
            <div class="col-xs-10 col-xs-offset-1 text-center">
              <h4>在线审核法律文件</h4>
              <p>专业律师为您检查合同文件，为您的权益保驾护航。</p>
              <p>一键上传，静候答复。</p>
            </div>
          </div>
        </div>
      <!-- Right Col Ends -->
      </div>
    <!-- Nested Row Ends -->
    </div>
  <!-- Nested Container Ends -->
  </section>
<!-- Intro Section Ends -->
<!-- featureSection Starts -->
		<section class="section-area practice-overview-section parallax text-center-xs">
  <!-- Nested Container Starts -->
    <div class="container">
      <h4 class="text-normal text-center">你的随身法律专家</h4>


    <!-- Nested Row Starts -->
      <ul class="row list-unstyled list-style-2 text-center">
      <!-- Col #1 Starts -->
        <li class="col-md-4  col-sm-12">
          <h6 class="text-normal">快速服务</h6>
          <p><i class="fa fa-question-circle"></i></p>
          <p>24小时内，得到回复</p>
        </li>
      <!-- Col #1 Ends -->
      <!-- Col #2 Starts -->
        <li class="col-md-4  col-sm-12">
          <h6 class="text-normal">隐私保护</h6>
          <p><i class="fa fa-lock" aria-hidden="true"></i></p>
          <p>信息私密，畅所欲言</p>

        </li>
      <!-- Col #2 Ends -->
      <!-- Col #3 Starts -->
        <li class="col-md-4 col-sm-12">
          <h6 class="text-normal">限时免费</h6>
          <p><i class="fa fa-credit-card"></i></p>
          <p>内测期间，免费提问。</p>
 
        </li>

      </ul>
    <!-- Nested Row Ends -->
    </div>
  <!-- Nested Container Ends -->
  </section>
<!-- feature Section Ends -->



<!-- Meet Our clients Starts -->
  <section class="section-area team-section">
  <!-- Nested Container Starts -->
    <div class="container text-center">
      <h3 class="main-heading-1">听听他们怎么说</h3>

    <!-- Team Members Carousel Starts -->
    <br>

      <div id="team-carousel" class="owl-carousel">
      <!-- Team #1 Starts -->
        <div class="team-col animation">
          <%= image_tag "http://ohjgz7qhu.bkt.clouddn.com/mastering-bitcoin.jpg", class:"img-responsive img-center" %>

          <div class="team-col-content">
            <h6>孙雁鸣</h6>
            <span class="designation text-light">伴律 &amp; 首席签约律师</span>
            <p> “伴律网让我能更加专注地提供法务咨询，普及法律，用自己的实际行动为全面依法治国的中国梦贡献了自己的心力” </p>

          </div>
        </div>
      <!-- Team #1 Ends -->
      <!-- Team #2 Starts -->
        <div class="team-col animation">
        <%= image_tag "http://ohjgz7qhu.bkt.clouddn.com/team-img2-b7ef01983f3621d707aa3261ae295f0bcb4e0841b03bfbcbb6d85564b1b2388b.jpg", class:"img-responsive img-center" %>
          <div class="team-col-content">
            <h6>黄喵</h6>
            <span class="designation text-light">某知名VC &amp; 投资人</span>
            <p>"感谢伴律， 让我在实现财务自由后，摆脱法律焦虑，安心入睡，实现收钱自由。"</p>

          </div>
        </div>
      <!-- Team #2 Ends -->
      <!-- Team #3 Starts -->
        <div class="team-col animation">
        <%= image_tag "http://ohjgz7qhu.bkt.clouddn.com/team-img3-f3db11029159c18a04ca6a5bba52dddeeabcae31fd1f44d5f529313b99b2b3f5.jpg", class:"img-responsive img-center" %>
          <div class="team-col-content">
            <h6>朱大维</h6>
            <span class="designation text-light"> 新兴科技公司 &amp; 首席执行官</span>
            <p>“伴律网让有了个贴身律师，随时咨询，及时得到专业解答。婚前协议请伴律网的梁律师看了一下，从此可以无顾虑去eatgehter 约饭。”</p>


          </div>
        </div>


      <!-- Team #3 Ends -->
      <!-- Team #4 Starts -->
        <div class="team-col animation">
          <%= image_tag "http://ohjgz7qhu.bkt.clouddn.com/team-img4-4aaade29a0cb3f3a4cb086df47ad5f285779ac9ca034c0d1774f406bf7001645.jpg", class:"img-responsive img-center" %>
          <div class="team-col-content">
            <h6>Eve</h6>
            <span class="designation text-light">《北京观察》 &amp; 作家</span>
            <p>"一年的陪伴，从开始完全没有法律意识，到现在没有任何法律困扰，可以说让我省去花费在版权的问题上，之前一直被这个问题困扰，感谢伴律。"</p>


          </div>
        </div>
      <!-- Team #4 Ends -->
      <!-- Team #5 Starts -->
        <div class="team-col animation">
          <%= image_tag "http://ohjgz7qhu.bkt.clouddn.com/team-img5-d097a8a5ba68001b92ad8d455dde133f4344eeaea019f314c656a69d0acdde47.jpg", class:"img-responsive img-center" %>
          <div class="team-col-content">
            <h6>黄里昂</h6>
            <span class="designation text-light"> 台北某夜店 &amp; 老板</span>
            <p>"自从有了拥有了伴律，我再也不用担心，涉及的法律问题，可以全身心的投入到工作，大大减少了我的后顾之忧。创造了更大的价值。"</p>


          </div>
        </div>
      <!-- Team #5 Ends -->
      <!-- Team #6 Starts -->
        <div class="team-col animation">
        <%= image_tag "http://ohjgz7qhu.bkt.clouddn.com/team-img6-06041e26f2994fa9dd5b4a082c9f3606c97364a78234e993b75fe0f60b55b91e.jpg", class:"img-responsive img-center" %>
          <div class="team-col-content">
            <h6>秦凤</h6>
            <span class="designation text-light">水果店 &amp; 店主</span>
            <p>”感谢，伴律网让我的水果卖向全世界同时，免去聘请单独法务的顾虑。我跟你讲，你们一定要用我们的服务，啊~ 免安装，一次上线，啊~”</p>


          </div>
        </div>
      <!-- Team #6 Ends -->
      <!-- Team #7 Starts -->
        <div class="team-col animation">
        <%= image_tag "http://ohjgz7qhu.bkt.clouddn.com/team-img7-5c3b3c56c9dccabe67592b1ddebdf09b061b0a7db773bc2bb1e2ce96626d7d08.jpg", class:"img-responsive img-center" %>
          <div class="team-col-content">
            <h6>陈小精</h6>
            <span class="designation text-light">能源公司 &amp; 巨擘</span>
            <p>“伴律网,雄起。”</p>

          </div>
        </div>

      </div>
    <!-- Team Members Carousel Ends -->
    </div>
  <!-- Nested Container Ends -->
  </section>
<!-- Meet Our clients Section Ends -->







<!-- Cases Stats Info Section Starts -->
  <section class="section-area cases-stats-info parallax">
  <!-- Nested Container Starts -->
    <div class="container text-center">
    <!-- Nested Row Starts -->
      <div class="row">
      <!-- #1 Starts -->
        <div class="col-md-4 col-sm-12">
          <h2 class="text-light badges-counter">200</h2>
          <h5 class="text-uppercase">份合同已经被审核</h5>
        </div>
      <!-- #1 Ends -->
      <!-- #2 Starts -->
        <div class="col-md-4  col-sm-12">
          <h2 class="text-light badges-counter">500</h2>
          <h5 class="text-uppercase">个问题得到回答</h5>
        </div>
      <!-- #2 Ends -->
      <!-- #3 Starts -->
        <div class="col-md-4 col-sm-12">
          <h2 class="text-light badges-counter">100</h2>
          <h5 class="text-uppercase">名客户满意使用</h5>
        </div>
      <!-- #3 Ends -->

      </div>
    <!-- Nested Row Ends -->
    </div>
  <!-- Nested Container Ends -->
  </section>
<!-- Cases Stats Info Section Ends -->









<!-- Free Consultation Section Starts -->
  <section class="section-area silver free-consultation-section text-center-sm text-center-xs">
  <!-- Heading Block Starts -->
    <div class="heading-block col-md-6 col-md-offset-3 col-xs-12 col-lg-12 col-lg-offset-2" id="heading-block">
      <div class="container">
        <h3>现在加入，首问免费</h3>
        <h5 class="sub-heading-1 text-light text-uppercase">越过法律高门槛，我们在你身边</h5>
      </div>
    </div>
  <!-- Heading Block Ends -->
  <!-- Nested Container Starts -->
    <div class="container">
    <!-- Nested Row Starts -->
      <div class="row">
      <!-- Form Starts -->
        <div class="col-md-6 col-md-offset-3 col-xs-12">
          <!-- form -->
          <%= simple_form_for  @temp_question,url: get_temp_question_welcome_index_path do |t| %>

          <div class="form-group">
              <%= t.input :content, label: '马上留下你的提问',input_html: {class: "form-control flat", rows:"6", id:"fs-msg",placeholder:"请留下你的问题"}%>
              <%= t.input :email, label: '邮箱',input_html: { class: "form-control"} %>
          </div>
          <%= t.submit "立即拥有私人律师", class: "btn  btn-secondary text-uppercase flat animation", data: { disable_with: "提交..." } %>
          <% end %>

        </div>
      <!-- Form Ends -->
      <!-- Image Block Starts -->

        </div>

      </div>
    <!-- Nested Row Ends -->
    </div>
  <!-- Nested Container Ends -->
  </section>
<!-- Free Consultation Section Ends -->
<!-- Clients Carousel Section Starts -->
  <section class="clients-section">
  <!-- Nested Container Starts -->
    <div class="container text-center">
      <h3 class="main-heading-1 light">媒体见证</h3>
    <!-- Carousel Starts -->
      <div id="clients-carousel" class="owl-carousel">
        <%= image_tag "http://ohjgz7qhu.bkt.clouddn.com/clients-carousel-img2-7b8bff404e8ada5af6a204f6af9de4713a63b3c480fa5713f77efb8b0fe3350e.png", class:"img-responsive img-center" %>
        <%= image_tag "http://ohjgz7qhu.bkt.clouddn.com/clients-carousel-img5-1939b443b58195067bde25f1252756250c1c0e7163f680597ae237ca989d42e3.png", class:"img-responsive img-center" %>
        <%= image_tag "http://ohjgz7qhu.bkt.clouddn.com/clients-carousel-img3-3b7af2338a4ceb67753cb5eccbe0bf1e62f8d1d8619bd5d57a539e9aa6e2bc52.png", class:"img-responsive img-center" %>
        <%= image_tag "http://ohjgz7qhu.bkt.clouddn.com/clients-carousel-img4-c04a8528c0ff80aa8112121038a54a6c5cc85efc4f0da8c0bc14511171e80aa2.png", class:"img-responsive img-center" %>
        <%= image_tag "http://ohjgz7qhu.bkt.clouddn.com/clients-carousel-img6-787d824c23ebdab7e71f29a848268ca97606c10de9a312704d4c8e7e1117878a.png", class:"img-responsive img-center" %>
        <%= image_tag "http://ohjgz7qhu.bkt.clouddn.com/clients-carousel-img1-019221e74dab0fb029b38815f959dc9a1dcd117b16bff3f51536bb6f398756a0.png", class:"img-responsive img-center" %>
        <%= image_tag "http://ohjgz7qhu.bkt.clouddn.com/clients-carousel-img7-3ff109c14b806488613dac7bc331b0a1fee390aa7f88e4c22bff6d2de7c810bd.png", class:"img-responsive img-center" %>
      </div>
    <!-- Carousel Ends -->
    </div>
  <!-- Nested Container Ends -->
  </section>
<!-- Clients Carousel Section Ends -->

app/views/welcome/join_us.html.erb
<h1>welcome</h1>

app/views/welcome/price.html.erb
<!-- Main Banner Area Starts -->
  <div class="main-banner">
    <div class="container">
      <h1 class="text-light text-center-sm text-center-xs">简单付费 <br>目的<br> 把注意力放在最重要的事情上 </h1>
    </div>
  </div>
<!-- Main Banner Area Ends -->


<!-- Main Container Starts -->
		<div class="main-container container text-center-xs">
			<h2 class="text-normal text-center">如何立即取得专业法律服务</h2>
    </div>
	<!-- Main Container Ends -->

    <section id="post-requirement-steps">
        <div class="container hidden-sm hidden-xs">
            <div class="row post-requirement-steps-images">

                <div class="col-sm-3">
                    <img src="https://ooo.0o0.ooo/2016/11/24/58368896503ed.png" class="img-circle" alt="屏幕快照 2016-11-24 14.25.03.png" title="屏幕快照 2016-11-24 14.25.03.png"/>

                    <p class="requirement-steps-details">填写您的需求，详细描述您的问题。</p>
                </div>
                <div class="col-sm-6 row">
                    <div class="col-sm-3 requirement-arrow">
                        <span class="glyphicons glyphicons-chevron-right"></span>
                    </div>
                    <div class="col-sm-6 requirement-middle-image">
                        <img src="https://ooo.0o0.ooo/2016/11/24/583688965bc0f.png" class="img-circle" alt="屏幕快照 2016-11-24 14.25.07.png" title="屏幕快照 2016-11-24 14.25.07.png"/>

                        <p class="requirement-steps-details">根据您的具体情况，选择不同的服务方案</p>
                    </div>

                </div>
                <div class="col-sm-3">
                    <img src="https://ooo.0o0.ooo/2016/11/24/58368897116b2.png" class="img-circle" alt="屏幕快照 2016-11-24 14.25.11.png" title="屏幕快照 2016-11-24 14.25.11.png"/>
                    <p class="requirement-steps-details">跟律师进行对话，取得专业法律意见</p>
                </div>
            </div>
        </div>
    </section>




    <!-- Practice Overview Section Starts -->
		<section class="section-area practice-overview-section parallax text-center-xs">
		<!-- Nested Container Starts -->
			<div class="container">
				<h4 class="text-normal text-center">价格方案</h4>

				<div class="row">
				<!-- Col #1 Starts -->
					<div class="col-sm-4 col-xs-12">

						<h5 class="text-uppercase text-normal">免费使用</h5>
						<p>无需繁琐注册</p>
            <p>首次登录</p>
            <p>免费向专业律师咨询</p>
            <% if current_user %>
						<%= link_to "立即购买", create_m_account_orders_path,class:"btn btn-outline text-uppercase flat animation" %>
            <% end %>
					</div>
				<!-- Col #1 Ends -->
				<!-- Col #2 Starts -->
					<div class="col-sm-4 col-xs-12">

						<h5 class="text-uppercase text-normal">月付费服务</h5>
						<p>
              无限次数提问</p>
              <p>不限次数提交法律文件审核
            </p>
            <p>
              在线下载文件

            </p>
              <% if current_user %>
						<%= link_to "按月支付", create_m_account_orders_path,method: :post,class:"btn btn-outline text-uppercase flat animation" %>
            <% end %>
					</div>
				<!-- Col #2 Ends -->
				<!-- Col #3 Starts -->
					<div class="col-sm-4 col-xs-12">

						<h5 class="text-uppercase text-normal">年付费服务</h5>
						<p>
              不限次数提出法律文件审核
						</p>
            <p>
              在线实务指导

            </p>
            <p>
              第一时间回复
            </p>
            <% if current_user %>
						<%= link_to "按年支付", create_y_account_orders_path,method: :post,class:"btn btn-outline text-uppercase flat animation" %>
              <% end %>
					</div>
				<!-- Col #4 Ends -->
				</div>
			<!-- Nested Row Ends -->
			</div>
		<!-- Nested Container Ends -->
		</section>
	<!-- Practice Overview Section Ends -->


  <!-- Testimonial Section Starts -->
  		<section class="section-area testimonials-section text-center">
  		<!-- Nested Container Starts -->
  			<div class="container">
  				<div class="row">
  					<div class="col-xs-10 col-xs-offset-1">
  						<h4 class="text-normal">律师见证</h4>

  						<h2><i class="fa fa-quote-left"></i></h2>
  					<!-- Carousel Starts -->
  						<div id="carousel-testimonials" class="carousel slide" data-ride="carousel">
  							<div class="row">
  								<div class="col-xs-8 col-xs-offset-2">
  								<!-- Wrapper For Slides Starts -->
  									<div class="carousel-inner">
  									<!-- Quote #1 Starts -->
  										<div class="item active">
  											<p>
  												伴律网让我能更加专注地提供法务咨询，普及法律，用自己的实际行动为全面依法治国的中国梦贡献了自己的心力”
  											</p>
  											<h4 class="text-normal">孙雁鸣</h4>

  										</div>
  									<!-- Quote #1 Ends -->
  									<!-- Quote #2 Starts -->
  										<div class="item">
  											<p>
  											伴律网让有了个贴身律师，随时咨询，及时得到专业解答。婚前协议请伴律网的梁律师看了一下，从此可以无顾虑去eatgehter 约饭。
  											</p>
  											<h4 class="text-normal">朱大维</h4>

  										</div>
  									<!-- Quote #2 Ends -->

  									</div>
  								<!-- Wrapper For Slides Ends -->
  								</div>
  							</div>
  						<!-- Controls Starts -->
  							<a class="left carousel-control" href="#carousel-testimonials" role="button" data-slide="prev">
  								<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
  								<span class="sr-only">Previous</span>
  							</a>
  							<a class="right carousel-control" href="#carousel-testimonials" role="button" data-slide="next">
  								<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
  								<span class="sr-only">Next</span>
  							</a>
  						<!-- Controls Ends -->
  						</div>
  					<!-- Carousel Ends -->
  					</div>
  				</div>
  			</div>
  		<!-- Nested Container Ends -->
  		</section>
  	<!-- Testimonial Section Ends -->





    <!-- END PACKAGES SECTION -->

app/views/welcome/sec_price.html.erb
<h1>为了保障您的问题得到专业的答复，我们网站从第二个问题开始进行收费咨询。</h1>
<h2><p>为什么我们要收费？</p></h2>
<h3><p>目前网上信息爆炸，免费法律咨询很多，但是从免费法律咨询得到真正解决方案的几率很低，用户虽然免费，但是却无法甄别所获得的答案是否适合自己的具体情况。
  多数稍微有点复杂的情况，就被告知需要到线下解决。我们伴律，立志于真正在网上解决问题，能不到线下就不到线下。</p></h3>
<h4><p>我们的律师都是5年以上经验的专业律师，线下咨询小时收费200-3000元不等。线上收费咨询，同样的服务，免除路途的限制。</p>
<p>除了问问题我们交了费还能享受什么服务？</p></h4>
  <h5>  <p>更多网站说明请见</p></h5>
  <li><%= link_to("收费说明",sec_price_path) %></li>
  <li><%= link_to("用户指南",help_term_path) %></li>

app/views/welcome/show.html.erb
<body>
  <div class="">

<div class="">
  <div class=" text-center">
     <p class="text-center"><h4 class="text-danger">告诉我们您需要解决的问题</h4></p>
      <p class="text-center"><h4 class="text-danger">选择服务方案</h4></p>
       <p class="text-center"><h4 class="text-danger">立即解决</h4></p>
</div>
  </div>
  <br><div class="container text-center">
    <img src="https://ooo.0o0.ooo/2016/11/24/58368896503ed.png" class="img-circle" alt="屏幕快照 2016-11-24 14.25.03.png" title="屏幕快照 2016-11-24 14.25.03.png" />
      <img src="https://ooo.0o0.ooo/2016/11/24/583688970350c.png" class="img-circle" alt="屏幕快照 2016-11-24 14.25.20.png" title="屏幕快照 2016-11-24 14.25.20.png" />
    <img src="https://ooo.0o0.ooo/2016/11/24/583688965bc0f.png" class="img-circle" alt="屏幕快照 2016-11-24 14.25.07.png" title="屏幕快照 2016-11-24 14.25.07.png" />
    <img src="https://ooo.0o0.ooo/2016/11/24/583688970350c.png" class="img-circle" alt="屏幕快照 2016-11-24 14.25.20.png" title="屏幕快照 2016-11-24 14.25.20.png" />
    <img src="https://ooo.0o0.ooo/2016/11/24/58368897116b2.png" class="img-circle" alt="屏幕快照 2016-11-24 14.25.11.png" title="屏幕快照 2016-11-24 14.25.11.png" />
  <br>
  </div>
  <br>
<div class="container text-center">
  <% if current_user %>
  <%= link_to "按月支付",create_m_account_orders_path, method: :post, class:
          "btn  btn-secondary text-uppercase flat animation"%>
  <%= link_to "按年支付",create_y_account_orders_path, method: :post, class:
          "btn  btn-secondary text-uppercase flat animation"%>
            <% else %>
            <%= link_to"马上拥有", new_user_registration_path ,class:
                    "btn  btn-secondary text-uppercase flat animation "%>

              <% end %>
</div>

<div class="container">
  <img src="https://ooo.0o0.ooo/2016/11/24/58368895df836.jpeg" alt="pricing1.002.jpeg" title="pricing1.002.jpeg" />
  <br>
</div>
</div>

</body>