config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :registrations }
#   as :user do
#   get 'users', :to => 'users#show', :as => :user_root # Rails 3
# end


  # 管理员路由
  namespace :admin do
    resources :questions do
      resources :answers
    end
    resources :documents
     resources :feedbacks
     resources :orders
    resources :conversations
    resources :users do
      member do
        post :change_to_user
        post :change_to_lawyer
        post :change_to_vip
        post :change_to_visitor
      end
    end
  end

  # 普通用户路由
  namespace :account do
    resources :documents
    resources :feedbacks

    #order路由
    resources :orders do
      collection do
        post :create_m
        post :create_y
      end
      #支付路由
      member do
        post :pay_with_alipay
        post :pay_with_wechat
      end
    end

    resources :users
    resources :questions do
      resources :answers
      resources :conversations do
        member  do
          get :show_lawyer
         end
      end

      # 评价系统
      collection do
        post :rating
        get  :new_document
      end

    end

  end

  # 律师路由
  namespace :lawyer do
    resources :users
    resources :questions do
      resources :answers
    end
    resources :documents do
      resources :feedbacks
    end

  end

  # f783-站内通知
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end


  resources :welcome do

    collection do
      # post :pricing  #支付路由
      # 获取路人问题
      post :get_temp_question
    end

  end

  get "/price", to: "welcome#price"
  get "/about_us", to: "welcome#about_us"
  get "/help_term", to: "welcome#help_term"
  get "/contact_us", to: "welcome#contact_us"
  get "/sec_price", to: "welcome#sec_price"


  root 'welcome#index'

end

app/models/lawyer.rb
class Lawyer < ApplicationRecord
  belongs_to :user

  # 律师与问题的多对多关系
  has_many :lawyer_answered_questions
  # has_and_belongs_to_many :questions

end

# == Schema Information
#
# Table name: lawyers
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers
  has_many :conversations, class_name: 'Conversation', foreign_key: 'question_id'
  has_many :notifications
  # 文档对象链接
  has_many :notifications, as: :notifiable



  # 律师与问题的多对多关系
  has_many :lawyer_answered_questions
  # has_and_belongs_to_many :lawyers
 


  # f1042-建立问题附件连接
  mount_uploader :attachment, Mailboxer::AttachmentUploader

  # f1113-问题和文件审核必须有描述
  validates :content, presence: true



  scope :recent, -> { order("created_at DESC")}
  scope :area, -> { order("area DESC")}
  scope :district, -> { order("district DESC")}

  # 变成被回答状态
  def answered!
    self.is_answered = true
    self.save
  end
  
  # 变成待回答状态
  def reopened!
    self.is_answered = false
    self.save   
  end


  def answered_lawyers
    q = self.lawyer_answered_questions
    users = q.map {|x| x.lawyer.user }
    return users
  end


end

# == Schema Information
#
# Table name: questions
#
#  id           :integer          not null, primary key
#  content      :text
#  area         :string
#  district     :string
#  user_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  is_answered  :boolean          default(FALSE)
#  attachment   :string
#  service_type :string
#

app/controllers/account/questions_controller.rb
class Account::QuestionsController < AccountController

  def index
    # binding.pry
    @questions = Question.where(user_id: current_user).recent
    # send_simple_message
  end

  # 新建问题
  def new
    @question = Question.new
  end

  # 问题
  def show
    @question = Question.find(params[:id])
    @answers = @question.answers
    @new_answer = Answer.new
    # f120
    # qid = @question.id.to_s
    # 查是否有关于此问题的回复
    @conversations = @question.conversations
    # binding.pry
  end

  # 编辑
  def edit
    @question = Question.find(params[:id])
  end

  # 建立
  def create
    # 如果用户是不是vip
    # 而且是当前用户已经问过了问题或者是第一个问题的追问，就重定向用户
    if !current_user.is_vip && (current_user.questions.present?)
      redirect_to price_path
    else
      @question = Question.new(question_params)
      # f787makeDocumentAsQuestions区分问题类型为『纯问题』与『文件审核』
      if question_params[:attachment].present?
        @question.service_type = 'ducument'
      else
        @question.service_type = 'question'
      end
      #

      @question.user = current_user
      if @question.save
        redirect_to account_questions_path, notice: "问题已发布!"
      else
        render :new
      end
      # 

    end
  end


  # 评价系统
  def rating
    # 获取message的参数
    conversation_id = params[:conversation_id]
    message_id = params[:message_id]
    score = params[:rating]

    # 找到指定的message
    conversation = Conversation.find(conversation_id.to_i)
    message = conversation.messages.find(message_id.to_i)
    # 为message评级
    message.rating = score
    message.save

    return 'success'
  end


  # 附件系统
  def new_document
    @question = Question.new
  end



  # 更新 暂不使用
  def update
    @question = Question.find(params[:id])
    @question.user = current_user
    if @question.update(question_params)
      redirect_to account_question_path(@question), notice: "问题已修改!"
    else
      render :back, notice: "修改失败!"
    end
  end

  # 删除 暂不使用
  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to :back
  end




  private

  # 问题参数
  def question_params
    params.require(:question).permit(:content,:area,:district,:attachment)
  end

  # 答案参数
  def answer_params
    params.require(:answer).permit(:content)
  end

end

app/controllers/admin/lawyers_controller.rb
class Admin::LawyersController < ApplicationController
  before_action :lawyer_required
  before_action :authenticate_user!

  layout "lawyer"

  # 只显示当前用户的问题
  def index
    @questions = Question.all
  end

  # 查看问题
  def show
    @question = Question.find(params[:id])
    @answers = @question.answers
    @new_answer = Answer.new
  end

# 回答问题
  def create
    @question = Question.find(params[:question_id])
    @new_answer = Answer.new(answer_params)
    @new_answer.user = current_user
    @new_answer.question = @question
    if @new_answer.save
      flash[:notice] = "回答成功！"
      redirect_to :back
    else
      flash[:alert] = "修改失败!"
      redirect_to :back
    end
  end

  # 更新回答
  def update
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
    if @answer.update(answer_params)
      redirect_to admin_question_path(@question), notice: "答案修改成功!"
    else
      render :back, notice: "答案修改失败!"
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:content)
  end



  # 增加需要律师登录
  def lawyer_required
    if !current_user.lawyer?
      redirect_to '/'
    end
  end
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < AdminController
  # 只显示当前用户的问题
  def index
    @user = current_user
    @questions = case params[:order]
    when 'by_area'
      Question.area
    when 'by_district'
      Question.district
    when "lawyer_area"
      my_area = @user.area
      Question.where(area:my_area)
    when  "lawyer_district"
      my_district = @user.district
      Question.where(district:my_district)
    else
      Question.recent
    end
  end

  # 查看问题
  def show
    @question = Question.find(params[:id])
    @answers = @question.answers
    @new_answer = Answer.new
    # f120
    # qid = @question.id.to_s
    # 查是否有关于此问题的回复
    dialog = @question.conversations.first
    # binding.pry
    if dialog.present?
      # 如果有就交给@message
      @messages = dialog.messages
      @conversation = dialog
    end
  end




end

app/controllers/lawyer/answers_controller.rb
class Lawyer::AnswersController < LawyerController


  # 回答问题
  def create
    @question = Question.find(params[:question_id])
    # 出题人
    akser = @question.user
    # 问题内容和问题id绑定
    subject = @question.content
    # 回答内容
    answer_content = answer_params[:content]
    # 获取附件
    attachment = answer_params[:attachment]
    # 对话id
    conversation_id = answer_params[:conversation_id]

    # mailboxer方法
    # 如果之前没有对话，就新建对话。如果有，就回复对话
    if conversation_id.blank?
      # 使用修正过得新send_message多加了一个参数
      conversation = current_user.send_message(akser ,answer_content ,subject , @question,true,attachment).conversation
      # 发送给用户回答问题的提醒
      send_notification!(akser.id, current_user.id, @question)
    else
      # 通过会话id获取会话
      conversation = @question.conversations.find(conversation_id)
      # binding.pry
      current_user.reply_to_conversation(conversation, answer_content,nil,true,true,attachment)
      # 发送给用户回答问题的提醒
      send_notification!(akser.id, current_user.id, @question)
    end
    # 更新律师与问题的多对多回答表
    lawyer_answer_question = LawyerAnsweredQuestion.new
    lawyer_answer_question.lawyer = current_user.lawyer
    lawyer_answer_question.question = @question
    lawyer_answer_question.save
    #

    # f470-变成已回答状态
    @question.answered!

    flash[:notice] = "回复成功"
    redirect_to :back
  end

  private

  def answer_params
    params.require(:answer).permit(:content,:conversation_id,:attachment)
  end

end

app/controllers/lawyer/questions_controller.rb
class Lawyer::QuestionsController < LawyerController


    def index
      @user = current_user
      @questions = case params[:order]
        #全部问题按照领域排序

        # when 'by_area'
        #   Question.area
        #   #全部问题按照地域排序
        # when 'by_district'
        #   Question.district
        #   #仅显示登陆的律师所在领域的问题
        # when 'lawyer_area'
        #   my_area = @user.area
        #   Question.where(area:my_area)
        #   #仅显示登陆的律师所在地区的问题
        # when 'lawyer_district'
        #   my_district = @user.district
        #   Question.where(district:my_district)
        # #仅显示登陆的律师所在地区及领域的问题并显示最新时间排序
        # when 'lawyer_two'
        #   my_district = @user.district
        #   my_area = @user.area
        #   Question.where(district:my_district,area:my_area).recent
        # f1195-fixLawyerQuestionSystem
        # 可回答问题
        when 'waiting_for_answer'
          # my_district = @user.district
          # my_area = @user.area
          fliter_questions = Question.all
          waiting_questions =  fliter_questions - current_user.answered_questions
          # puts waiting_questions
          # 数组按时间倒序排列
          waiting_questions.sort_by{ |i| i.created_at }.reverse
        # 答过的问题
        when 'already_answered'
          # 数组按时间倒序排列
          current_user.answered_questions.sort_by{ |i| i.created_at }.reverse
        #
        else
          #所有问题按照最新时间排序
          Question.recent
        end

    end


    #查看问题
    def show
      @question = Question.find(params[:id])
      @answers = @question.answers
      @new_answer = Answer.new

      # f120

      # 查是否有关于此问题的回复
      dialog = @mailbox.conversations.find_by(question_id: @question)

      # binding.pry
      if dialog.present?
        # 如果有就交给@message
        # 生产异常message序列，使用逆序
        @messages = dialog.messages.order(created_at: :ASC)

        # binding.pry
        @conversation = dialog
      end

    end




end

app/controllers/lawyer/users_controller.rb
class Lawyer::UsersController < LawyerController
 

  def index
    @user = current_user
    @lawyer_rating = average_rating(current_user)
  end


  def edit
    @user = current_user
    @user = User.find(params[:id])
  end


  def show
    @user = current_user

  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to lawyer_users_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:user_name,:email,:user_avatar,:district,:area,:lawfirm,:certificate,:certificate_number)
  end

end

app/controllers/lawyer_controller.rb
class LawyerController < ApplicationController
    before_action :authenticate_user!
    before_action :lawyer_required
    before_action :get_mailbox
    layout "lawyer"


end

app/helpers/account/questions_helper.rb
module Account::QuestionsHelper
end

app/helpers/admin/lawyers_helper.rb
module Admin::LawyersHelper
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/helpers/lawyer/answers_helper.rb
module Lawyer::AnswersHelper
end

app/helpers/lawyer/question_helper.rb
module Lawyer::QuestionHelper
end

app/helpers/lawyer/questions_helper.rb
module Lawyer::QuestionsHelper
end

app/helpers/lawyer/users_helper.rb
module Lawyer::UsersHelper
end

app/helpers/lawyer_helper.rb
module LawyerHelper
end

app/views/lawyer/questions/_form_for_lawyer.html.erb
    <!-- 律师表单 -->
    <%= simple_form_for @new_answer ,url: lawyer_question_answers_path(@question) do |a| %>
    <% if @conversation.present? %>
    <!-- <h1>对话id:<%#= @conversation.id %></h1> -->
    <!-- 隐藏提交当前会话id -->
    <%= a.input :conversation_id, :as => :hidden, :input_html => { :value => @conversation.id } %>

    <% end %>

    <div class="form-group">
        <%= a.input :content, label: '法律意见：',input_html: { class: "form-control",rows: "15"} %>


    </div>

    <div class="form-group">
        <%= a.input :attachment ,label: '附件'%>
    </div>

    <%= a.submit "提交", class: "btn  btn-secondary text-uppercase flat animation", data: { disable_with: "提交..." } %>
    <% end %>

app/views/lawyer/questions/_history_messages.html.erb
  <!-- 律师端历史消息 -->
    <% if @messages.present? %>
      <% @messages.each do |m| %>

      <h6 class="text-center"><small><em> — <%= time_format(m.created_at) %> — </em></small></h6>

        <!-- 历史消息 -->
        <% if m.sender == current_user %>
          <!-- 律师对话样式 -->
          <blockquote class="blockquote-reverse">
            <div class="media">
              <div class="media-body">
                <h3 class="media-heading">我</h3>
                <h5><%= simple_format(m.body) %></h5>



                <!-- 附件显示（当前上传pdf有问题） -->
                <% if m.attachment.present? %>
                  <div class="pull-right">

                    <!-- 附件 -->
                    <a href="<%= m.attachment.url %>" download="" target="_blank">

                      <h4><i class="fa fa-file-text" aria-hidden="true"></i></h4>
                      <p><%= m.attachment.file.filename %></p>

                    </a>
                    <!--  -->


                  </div>
                <% end %>
                <!-- 附件显示（当前上传pdf有问题） -->




              </div>
              <a class="media-right" href="#">
                <!-- 用户头像 -->
                <%= render(partial: "common/user_img",locals: {user: current_user}) %>
                <!-- 用户头像 -->
              </a>
            </div>
          </blockquote>






        <!-- 律师端的评价系统 -->

          <!-- <hr> -->
          <p class="text-center">
            <!-- 如果已评分，则显示评分 -->
            <% if m.rating.present? %>
              <div id="raty-for-message-<%= m.id %>" class="text-center"></div>
            <% end %>
          </p>

          <hr>

          <script>
          $(function() {

            // 允许评分的对象
            var ratableObj = $('#rating-for-message-<%= m.id %>');
            initRating(ratableObj);
            // 已经评过分的对象
            var unRatableObj = $('#raty-for-message-<%= m.id %>');
            lockRating(unRatableObj,'<%= m.rating %>');


            // 初始化rating选框
            function initRating(obj) {
              obj.raty({
                // 设置rating路径
                path:"https://ooo.0o0.ooo/2016/11/29/",
                starOff: '583d4cc6dae6a.png',
                starOn: '583d4cc7067dc.png',
                size: 32,
                click: function(score, evt) {
                  // ajax提交
                  ajaxRating(score);
                  // 锁定rating
                  lockRating(ratableObj,score)
                }
              });
            }



            // ajax提交评级
            function ajaxRating(score) {
              $.ajax({
                url: '<%= rating_account_questions_path %>',
                type: 'POST',
                dataType: 'json',
                data: {
                  'conversation_id' : <%= @conversation.id %>,
                  'message_id' : <%= m.id %>,
                  'rating': score
                },
              })
              .done(function() {
                console.log("raty success");
              })
              .fail(function() {
                console.log("raty error");
              })
              .always(function() {
                console.log("raty complete");
              });
            }




            // 锁定星星不可重新提交
            function lockRating(obj,score) {
              // 锁定部分样式
              obj.raty({
                // 设置rating路径
                path:"https://ooo.0o0.ooo/2016/11/29/",
                starOff: '583d4cc6dae6a.png',
                starOn: '583d4cc7067dc.png',
                size: 32,
                readOnly: true, score: score
              });
            }


          });
          </script>

          <!-- 律师端的评价系统 -->




















        <% else %>
          <!-- 用户的对话样式 -->
          <blockquote>
            <div class="media">
              <a class="media-left" href="#">
                <!-- 用户头像 -->
                <%= render(partial: "common/user_img",locals: {user: m.sender}) %>
                <!-- 用户头像 -->
              </a>
              <div class="media-body">
                <% if m.sender.user_name.present? %>
                  <h3 class="media-heading"><%= m.sender.user_name %></h3>
                <% else %>
                  <h3 class="media-heading">客户</h3>
                <% end %>
                <h5><%= simple_format(m.body) %></h5>





                <!-- 附件显示（当前上传pdf有问题） -->
                <% if m.attachment.present? %>

                  <div class="pull-left">

                    <%= image_tag(m.attachment.url, class: "thumbnail") %>
                    <p class="pull-left"><%= m.attachment.file.filename %></p>

                    <a href="<%= m.attachment.url %>" download="" target="_blank">
                      <button type="button" class="btn  btn-secondary text-uppercase flat animation btn-xs pull-right">下载</button>
                    </a>
                  </div>

                <% end %>
                <!-- 附件显示（当前上传pdf有问题） -->









              </div>
            </div>
          </blockquote>

        <% end %>
        <!-- 历史消息 -->



      <% end %>
    <% end %>

app/views/lawyer/questions/index.html.erb
<div class="container-fluid well">
   
          <table class="table table-bordered table-condensed table-hover">

            <thead>
              <tr>
                <th>
                用户信息
                </th>
                <th>
                问题领域
                </th>
                <th>
                  所在地域
                </th>
                <th>
                  问题缩略
                </th>
                <th>
                  更新时间
                </th>
                <th>
                  问题编号
                </th>
              </tr>
            </thead>

              <% if @questions.present? %>

                <% @questions.each do |question|%>
                  <!-- 筛除用户注销的情况 -->
                  <% if question.user.present? %>
                    <tr>
                      <td><%= question.user.email %></td>
                      <td><%= question.area %></td>
                      <td><%= question.district %></td>
                      <td><%= link_to(question.content.first(8),lawyer_question_path(question)) %></td>
                      <td><%= question.updated_at %></td>
                      <td><%= link_to(question.id,lawyer_question_path(question)) %></td>
                    </tr>
                  <% end %>
                  <!--  -->
                <% end %>

              <% end %>
          </table>
        </div>

app/views/lawyer/questions/show.html.erb
<div class="col-md-12 container-fluid well">

  <!-- 客户问题 -->
  <h4>问题： <%= @question.content %></h4>
  <h6>领域： <%= @question.area %></h6>
  <!-- <h6>地区： <%#= @question.district %></h6> -->

  <!-- 附件显示预览 -->
  <% if @question.attachment.present? %>
    <div>

      <!-- 附件 -->
      <a href="<%= @question.attachment.url %>" download="" target="_blank">

        <h4><i class="fa fa-file-text" aria-hidden="true"></i></h4>
        <p><%= @question.attachment.file.filename %></p>

      </a>
      <!--  -->

    </div>
  <% end %>
  <!-- 附件显示预览 -->

  <br>

  <hr>

  <!-- 历史消息 -->
  <%= render 'history_messages' %>



  <!-- 如果最后一条是自己的留言，则不让再追答 -->
  <% if i_send_last_message(@messages) %>
    <div class="alert alert-success text-center" role="alert">已回复</div>
    <!-- 如果没人回答，可以回答 -->
  <% else %>
    <!-- 律师回答表单 -->
    <%= render 'form_for_lawyer' %>
  <% end %>



</div>
</div>
</div>
</div>