config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :registrations }
#   as :user do
#   get 'users', :to => 'users#show', :as => :user_root # Rails 3
# end


  # 管理员路由
  namespace :admin do
    resources :questions do
      resources :answers
    end
    resources :documents
     resources :feedbacks
     resources :orders
    resources :conversations
    resources :users do
      member do
        post :change_to_user
        post :change_to_lawyer
        post :change_to_vip
        post :change_to_visitor
      end
    end
  end

  # 普通用户路由
  namespace :account do
    resources :documents
    resources :feedbacks

    #order路由
    resources :orders do
      collection do
        post :create_m
        post :create_y
      end
      #支付路由
      member do
        post :pay_with_alipay
        post :pay_with_wechat
      end
    end

    resources :users
    resources :questions do
      resources :answers
      resources :conversations do
        member  do
          get :show_lawyer
         end
      end

      # 评价系统
      collection do
        post :rating
        get  :new_document
      end

    end

  end

  # 律师路由
  namespace :lawyer do
    resources :users
    resources :questions do
      resources :answers
    end
    resources :documents do
      resources :feedbacks
    end

  end

  # f783-站内通知
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end


  resources :welcome do

    collection do
      # post :pricing  #支付路由
      # 获取路人问题
      post :get_temp_question
    end

  end

  get "/price", to: "welcome#price"
  get "/about_us", to: "welcome#about_us"
  get "/help_term", to: "welcome#help_term"
  get "/contact_us", to: "welcome#contact_us"
  get "/sec_price", to: "welcome#sec_price"


  root 'welcome#index'

end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
  <!-- Footer Starts -->
		<footer class="main-footer" >
		<!-- Footer Links Starts -->
			<div class="footer-links text-center-xs">
			<!-- Nested Container Starts -->
				<div class="container">
				<!-- Nested Row Starts -->
					<div class="row">
					<!-- Foot Col #1 Starts -->
						<div class="col-md-6   col-sm-12 hidden-xs">
							<h4 class="text-light-color">关于伴律网</h4>
							<p>伴律网是一家旨在为用户提供在线法律咨询的服务网站。拥有伴律网，用户等于拥有自己的专属律师。拥有伴律网，企业相当于拥有自己的法律顾问。方便快捷，专业咨询，不只是解决问题，更重要的是防范问题的发生。</p>
							<p>伴律网旨在为用户提供法律咨询的同时，提高用户的法律基础知识。</p>
<!-- 							<ul class="list-unstyled list-inline sm-foot-links">
								<li class="animation"><a href="#"><i class="fa fa-twitter-square"></i></a></li>
								<li class="animation"><a href="#"><i class="fa fa-facebook-square"></i></a></li>
								<li class="animation"><a href="#"><i class="fa fa-linkedin-square"></i></a></li>
								<li class="animation"><a href="#"><i class="fa fa-google-plus-square"></i></a></li>
								<li class="animation"><a href="#"><i class="fa fa-pinterest-square"></i></a></li>
							</ul> -->
						</div>
					<!-- Foot Col #1 Ends -->

					<!-- Foot Col #2 Starts -->
						<div class="col-md-3 col-sm-12">
							<h4 class="text-light-color">联系信息</h4>
							<p> 中国北京朝阳区建外 SOHO </p><br>
							<ul class="list-unstyled">
								<li><span class="glyphicon glyphicon-earphone"></span> &nbsp;400 345 678 9630</li>
								<li><span class="glyphicon glyphicon-envelope"></span>
								<a href="mailto:laywerconsult@lawyerconsult.com"> &nbsp;whenmgonetest@163.com</a></li>
							</ul>
						</div>
					<!-- Foot Col #2 Ends -->
						<div class="col-md-3 hidden-xs text-center">
							<p>安卓版客户端下载</p>
							<p><img src="https://ooo.0o0.ooo/2016/12/02/5840f42abdbeb.png" alt="andorid_lvban.png" title="andorid_lvban.png" /></p>

						</div>


					</div>
				<!-- Nested Row Ends -->
				</div>
			<!-- Nested Container Ends -->
			</div>
		<!-- Footer Links Ends -->
		<!-- Copyright Starts -->
			<div class="copyright">
						<div class="copyright text-center">伴律 &copy; 2016, All Rights Reserved.</div>

					</div>
			<!-- Nested Container Ends -->
		<!-- Copyright Ends -->
		</footer>
	<!-- Footer Ends -->

app/views/common/_navbar.html.erb
<header class="main-header">


<!-- Nested Container Starts -->
  <div class="container">
  <!-- Nested Row Starts -->
    <div class="row">
    <!-- Logo Starts -->
      <div class="col-md-3 col-sm-4 col-xs-12">


        <%=link_to(image_tag("logo.png",alt:"Law Attorney", class:"img-responsive img-center-xs logo"),root_path)%>
      </div>
    <!-- Logo Ends -->
    <!-- Right Col Starts -->
      <div class="col-md-9 col-sm-8 col-xs-12 hidden-xs">
      <!-- Header Links Starts -->
        <ul class="list-unstyled list-inline header-links text-right-lg text-right-md text-right-sm text-center-xs text-light">
          <li><%= link_to("价格方案",price_path) %></li>
          <li><%= link_to("加入我们",contact_us_path) %></li>
          <li><%= link_to("关于我们",about_us_path) %></li>
          <li><%= link_to("用户指南",help_term_path) %></li>
          


          <!-- <li><a href="#">Team Members</a></li> -->
        </ul>
      <!-- Header Links Ends -->
      <!-- Starts -->
        <ul class="list-unstyled list-inline header-info text-center-xs pull-right-lg pull-right-md pull-right-sm">
          <li class="hidden-sm">

          <a href="javascript:void(0)" onclick="_MEIQIA('showPanel')" class="btn btn-secondary text-uppercase animation flat"><i class="fa fa-comments"></i>24小时在线客服</a>

          </li>
          <li class="clearfix">
            <i class="fa fa-map-marker pull-left"></i>
            <span class="pull-left">
              <h6>建外 SOHO </h6>
                中国北京朝阳区
            </span>
          </li>
          <li class="clearfix">
            <i class="fa fa-phone pull-left"></i>
            <span class="pull-left">
              <h6>400 345 678 9630</h6>
              免费咨询电话
            </span>
          </li>
        </ul>
      <!-- Ends -->
      </div>
    <!-- Right Col Ends -->
    </div>
  <!-- Nested Row Ends -->
  </div>
<!-- Nested Container Ends -->
</header>
<!-- Main Header Ends -->
<!-- Main Menu Starts -->
<nav id="nav" class="main-menu navbar flat">
<!-- Nested Container Starts -->
  <div class="container">
  <!-- Nav Header Starts -->
    <div class="navbar-header">
      <button type="button" class="btn btn-navbar navbar-toggle flat animation" data-toggle="collapse" data-target=".navbar-cat-collapse">
        <span class="sr-only">Toggle Navigation</span>
        <i class="fa fa-bars"></i>
      </button>
<!--mobile display notifications-->
      <div class="hidden-md hidden-sm hidden-lg smallnotificationIcon">
            <li type="button" class="btn  btn-notification btn-secondary btn-secondary-black text-uppercase flat animation pull-right"
                    data-container="body" data-toggle="popover" data-placement="bottom"
                    data-content="

                    <!-- 插入的html触发码 -->
                    <% if @notifications.present? %>
                      <% @notifications.each do |n| %>

                        <!-- 律师见到的 -->
                        <% if current_user.lawyer? %>
                          <p><%= n.actor.user_name %>追问了
                            <a href=<%= lawyer_question_path(n.notifiable) %>><%= n.notifiable.content %></a>
                          </p>
                        <!-- 普通用户见到的 -->
                        <% else %>
                          <p><%= n.actor.user_name %>回复了
                            <a href=<%= account_question_path(n.notifiable) %>><%= n.notifiable.content %></a>
                          </p>
                        <% end %>

                      <% end %>
                    <% else %>
                      <p>没有新的消息</p>
                    <% end %>

                    ">
                <i class="fa fa-bell-o fa-notification" aria-hidden="true">

                  <!-- f1275-cgNumToRedPoint 提醒换成原点-->
                  <% if @notifications.present? %>
                    <div class='notification-point text-center btn-danger'>
                      <%= @notifications.count %>
                    </div>
                  <% end %>
                  <!--  -->

                </i>
            </li>
        </div>


    </div>






  <!-- Nav Header Ends -->
  <!-- Navbar Cat collapse Starts -->
    <div class="collapse navbar-collapse navbar-cat-collapse animation">






<!--       <ul class="nav navbar-nav text-uppercase text-bold">
        <li class="active">
         <%# if !current_user %>

              <%# elsif current_user.admin? %>
              <%#= link_to("管理员面板", admin_questions_path) %>

              <%# elsif current_user.lawyer? %>

               <%#= link_to("律师面板",lawyer_questions_path(:order => "waiting_for_answer")) %>
              <%# else %>
              <%#= link_to("我的动态", account_questions_path) %>
          <%# end %>

        </li>

      </ul> -->




      <ul class="nav navbar-nav navbar-right text-right-lg text-right-md ">
        <li class="dropdown pull-right">

                      <% if !current_user %>

                    <li><%= link_to(content_tag(:i, '注册', class: 'fa fa-user-circle'), new_user_registration_path) %></li>


                     <li><%= link_to(content_tag(:i, '登入', class: 'fa fa-sign-in'), new_user_session_path) %></li>
                    <% else %>
                   <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                          你好，<% if current_user.user_name.present? %>
                          <%= current_user.user_name %>
                          <% else %>
                          <%= current_user.email %>
                          <% end %>
                          <b class="caret"></b>
                      </a>

                      <ul class="dropdown-menu">

                          <% if current_user.admin? %>
                          <!-- <li> <%= link_to(content_tag(:i, ' 管理员面板', class: 'fa fa-universal-access'), admin_questions_path ) %> </li> -->
                          <li> <%= link_to(content_tag(:i, ' 管理员中心', class: 'fa fa-users'), admin_users_path ) %> </li>
                          <li> <%= link_to(content_tag(:i, ' 律师中心', class: 'fa fa-vcard'), lawyer_users_path ) %> </li>

                          <% elsif current_user.lawyer? %>
                          <!-- <li> <%= link_to(content_tag(:i, ' 律师面板', class: 'fa fa-university'), lawyer_questions_path(:order => "waiting_for_answer") ) %> </li> -->
                          <li> <%= link_to(content_tag(:i, ' 律师中心', class: 'fa fa-vcard'), lawyer_users_path ) %> </li>
                          <% else %>
                          <!-- <li> <%= link_to(content_tag(:i, ' 我的动态', class: 'fa fa-user-secret'), account_questions_path ) %> </li> -->
                          <li> <%= link_to(content_tag(:i, ' 用户中心', class: 'fa fa-university'), account_users_path ) %> </li>

                          <% end %>

                           <li> <%= link_to(content_tag(:i, ' 登出', class: 'fa fa-sign-out'), destroy_user_session_path, method: :delete) %> </li>
                      </ul>

                    </li>
                      <% end %>

          </ul>
        </li>




        <!-- 添加提醒系统 -->
        <div class="notificationIcon hidden-xs">
          <li type="button" class="btn btn-notification btn-secondary btn-secondary-black text-uppercase flat animation pull-right"
                  data-container="body" data-toggle="popover" data-placement="bottom"
                  data-content="

                  <!-- 插入的html触发码 -->
                  <% if @notifications.present? %>
                    <% @notifications.each do |n| %>

                      <!-- 律师见到的 -->
                      <% if current_user.lawyer? %>
                        <p><%= n.actor.user_name %>追问了
                          <a href=<%= lawyer_question_path(n.notifiable) %>><%= n.notifiable.content %></a>
                        </p>
                      <!-- 普通用户见到的 -->
                      <% else %>
                        <p><%= n.actor.user_name %>回复了
                          <a href=<%= account_question_path(n.notifiable) %>><%= n.notifiable.content %></a>
                        </p>
                      <% end %>

                    <% end %>
                  <% else %>
                    <p>没有新的消息</p>
                  <% end %>

                  ">
              <i class="fa fa-bell-o fa-notification" aria-hidden="true">

                <!-- f1275-cgNumToRedPoint 提醒换成原点-->
                <% if @notifications.present? %>
                  <div class='notification-point text-center btn-danger'>
                    <%= @notifications.count %>
                  </div>
                <% end %>
                <!--  -->

              </i>
          </li>
      </div>

        <!--  -->




      </ul>
    </div>
  <!-- Navbar Cat collapse Ends -->


  </div>
<!-- Nested Container Ends -->
</nav>









<script>
$(function (){
  // 绑定触发条件
  $(".btn-notification").popover({
            trigger:'click', //触发方式
            html: true, // 为true的话，data-content里就能放html代码了
        });

  // 标记已读
  $('.btn-notification').on('shown.bs.popover', function () {
      $(".notification-point").remove();
      $.ajax({
      url: '<%= mark_as_read_notifications_path %>',
      type: 'POST',
      dataType: 'json',
      data: {'read': 'true'},
      })
      .done(function() {
        console.log("success");
      })
      .fail(function() {
        console.log("error");
      })
      .always(function() {
        console.log("complete");
      });
  })
  //




});
</script>






<!-- 美洽代码 -->
<script type='text/javascript'>
    (function(m, ei, q, i, a, j, s) {
        m[i] = m[i] || function() {
            (m[i].a = m[i].a || []).push(arguments)
        };
        j = ei.createElement(q),
            s = ei.getElementsByTagName(q)[0];
        j.async = true;
        j.charset = 'UTF-8';
        j.src = '//static.meiqia.com/dist/meiqia.js';
        s.parentNode.insertBefore(j, s);
    })(window, document, 'script', '_MEIQIA');
    _MEIQIA('entId', 42733);
</script>
<script>
    // 你可以自己的代码中选择合适的时机来调用手动初始化
    _MEIQIA('init');
</script>
<!--  -->

app/views/common/_page_navbar.html.erb
<header class="main-header">


<!-- Nested Container Starts -->
  <div class="container">
  <!-- Nested Row Starts -->
    <div class="row">
    <!-- Logo Starts -->
      <div class="col-md-3 col-sm-4 col-xs-12">
        <%= image_tag("logo.png",alt:"Law Attorney", class:"img-responsive img-center-xs hidden-xs logo")%>
      </div>
    <!-- Logo Ends -->
    <!-- Right Col Starts -->
    <div class="col-md-9 col-sm-8 col-xs-12 hidden-xs">
    <!-- Header Links Starts -->
      <ul class="list-unstyled list-inline header-links text-right-lg text-right-md text-right-sm text-center-xs text-light">
        <li><%= link_to("价格方案",price_path) %></li>
        <li><a href=/joinus>加入我们</a></li>
        <li><a href=/aboutus>关于我们</a></li>
        <li><a href=/mapguide>用户指南</a></li>


       
        <!-- <li><a href="#">Team Members</a></li> -->
      </ul>
    <!-- Header Links Ends -->
    <!-- Starts -->
      <ul class="list-unstyled list-inline header-info text-center-xs pull-right-lg pull-right-md pull-right-sm">
        <li class="hidden-sm">

        <a href="javascript:void(0)" onclick="_MEIQIA('showPanel')" class="btn btn-secondary text-uppercase animation flat"><i class="fa fa-comments"></i>24小时在线客服</a>

        </li>
        <li class="clearfix">
          <i class="fa fa-map-marker pull-left"></i>
          <span class="pull-left">
            <h6>建外 SOHO </h6>
              中国北京朝阳区
          </span>
        </li>
        <li class="clearfix">
          <i class="fa fa-phone pull-left"></i>
          <span class="pull-left">
            <h6>400 345 678 9630</h6>
            免费咨询电话
          </span>
        </li>
      </ul>
    <!-- Ends -->
    </div>
  <!-- Right Col Ends -->
  </div>
<!-- Nested Row Ends -->
</div>
<!-- Nested Container Ends -->
</header>
<!-- Main Header Ends -->
<!-- Main Menu Starts -->
<nav id="nav" class="main-menu navbar flat">
<!-- Nested Container Starts -->
<div class="container">
<!-- Nav Header Starts -->
  <div class="navbar-header">
    <button type="button" class="btn btn-navbar navbar-toggle flat animation" data-toggle="collapse" data-target=".navbar-cat-collapse">
      <span class="sr-only">Toggle Navigation</span>
      <i class="fa fa-bars"></i>
    </button>
<!--mobile display notifications-->
    <div class="hidden-md hidden-sm hidden-lg smallnotificationIcon">
          <li type="button" class="btn  btn-notification btn-secondary btn-secondary-black text-uppercase flat animation pull-right"
                  data-container="body" data-toggle="popover" data-placement="bottom"
                  data-content="

                  <!-- 插入的html触发码 -->
                  <% if @notifications.present? %>
                    <% @notifications.each do |n| %>

                      <!-- 律师见到的 -->
                      <% if current_user.lawyer? %>
                        <p><%= n.actor.user_name %>追问了
                          <a href=<%= lawyer_question_path(n.notifiable) %>><%= n.notifiable.content %></a>
                        </p>
                      <!-- 普通用户见到的 -->
                      <% else %>
                        <p><%= n.actor.user_name %>回复了
                          <a href=<%= account_question_path(n.notifiable) %>><%= n.notifiable.content %></a>
                        </p>
                      <% end %>

                    <% end %>
                  <% else %>
                    <p>没有新的消息</p>
                  <% end %>

                  ">
              <i class="fa fa-bell-o fa-notification" aria-hidden="true">

                <!-- f1275-cgNumToRedPoint 提醒换成原点-->
                <% if @notifications.present? %>
                  <div class='notification-point text-center btn-danger'>
                    <%= @notifications.count %>
                  </div>
                <% end %>
                <!--  -->

              </i>
          </li>
      </div>


  </div>






<!-- Nav Header Ends -->
<!-- Navbar Cat collapse Starts -->
  <div class="collapse navbar-collapse navbar-cat-collapse animation">




<!--     <ul class="nav navbar-nav text-uppercase text-bold">
      <li class="active">
       <%# if !current_user %>

            <%# elsif current_user.admin? %>
            <%#= link_to("管理员面板", admin_questions_path) %>

            <%# elsif current_user.lawyer? %>

             <%#= link_to("律师面板",lawyer_questions_path(:order => "waiting_for_answer")) %>
            <%# else %>
            <%#= link_to("我的动态", account_questions_path) %>
        <%# end %>


      </li>

    </ul> -->















    <ul class="nav navbar-nav navbar-right text-right-lg text-right-md ">


      <li class="dropdown pull-right">

                    <% if !current_user %>

                  <li><%= link_to(content_tag(:i, '注册', class: 'fa fa-user-circle'), new_user_registration_path) %></li>


                   <li><%= link_to(content_tag(:i, '登入', class: 'fa fa-sign-in'), new_user_session_path) %></li>
                  <% else %>
                 <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        你好，<% if current_user.user_name.present? %>
                        <%= current_user.user_name %>
                        <% else %>
                        <%= current_user.email %>
                        <% end %>
                        <b class="caret"></b>
                    </a>

                    <ul class="dropdown-menu">

                        <% if current_user.admin? %>
                        <!-- <li> <%= link_to(content_tag(:i, ' 管理员面板', class: 'fa fa-universal-access'), admin_questions_path ) %> </li> -->
                        <li> <%= link_to(content_tag(:i, ' 管理员中心', class: 'fa fa-users'), admin_users_path ) %> </li>
                        <li> <%= link_to(content_tag(:i, ' 律师中心', class: 'fa fa-vcard'), lawyer_users_path ) %> </li>

                        <% elsif current_user.lawyer? %>
                        <!-- <li> <%= link_to(content_tag(:i, ' 律师面板', class: 'fa fa-university'), lawyer_questions_path(:order => "waiting_for_answer") ) %> </li> -->
                        <li> <%= link_to(content_tag(:i, ' 律师中心', class: 'fa fa-vcard'), lawyer_users_path ) %> </li>
                        <% else %>
                        <!-- <li> <%= link_to(content_tag(:i, ' 我的动态', class: 'fa fa-user-secret'), account_questions_path ) %> </li> -->
                        <li> <%= link_to(content_tag(:i, ' 用户中心', class: 'fa fa-university'), account_users_path ) %> </li>
                        <!-- <li> <%= link_to(content_tag(:i, ' 支付中心', class: 'fa fa-paypal'), account_orders_path ) %> </li> -->
                        <% end %>

                         <li> <%= link_to(content_tag(:i, ' 登出', class: 'fa fa-sign-out'), destroy_user_session_path, method: :delete) %> </li>
                    </ul>

                  </li>
                    <% end %>

        </ul>
      </li>




      <!-- 添加提醒系统 -->
      <div class="notificationIcon hidden-xs">
        <li type="button" class="btn btn-notification btn-secondary btn-secondary-black text-uppercase flat animation pull-right"
                data-container="body" data-toggle="popover" data-placement="bottom"
                data-content="

                <!-- 插入的html触发码 -->
                <% if @notifications.present? %>
                  <% @notifications.each do |n| %>

                    <!-- 律师见到的 -->
                    <% if current_user.lawyer? %>
                      <p><%= n.actor.user_name %>追问了
                        <a href=<%= lawyer_question_path(n.notifiable) %>><%= n.notifiable.content %></a>
                      </p>
                    <!-- 普通用户见到的 -->
                    <% else %>
                      <p><%= n.actor.user_name %>回复了
                        <a href=<%= account_question_path(n.notifiable) %>><%= n.notifiable.content %></a>
                      </p>
                    <% end %>

                  <% end %>
                <% else %>
                  <p>没有新的消息</p>
                <% end %>

                ">
            <i class="fa fa-bell-o fa-notification" aria-hidden="true">

              <!-- f1275-cgNumToRedPoint 提醒换成原点-->
              <% if @notifications.present? %>
                <div class='notification-point text-center btn-danger'>
                  <%= @notifications.count %>
                </div>
              <% end %>
              <!--  -->

            </i>
        </li>
    </div>

      <!--  -->




    </ul>
  </div>
<!-- Navbar Cat collapse Ends -->


</div>
<!-- Nested Container Ends -->
</nav>









<script>
$(function (){
// 绑定触发条件
$(".btn-notification").popover({
          trigger:'click', //触发方式
          html: true, // 为true的话，data-content里就能放html代码了
      });

// 标记已读
$('.btn-notification').on('shown.bs.popover', function () {
    $(".notification-point").remove();
    $.ajax({
    url: '<%= mark_as_read_notifications_path %>',
    type: 'POST',
    dataType: 'json',
    data: {'read': 'true'},
    })
    .done(function() {
      console.log("success");
    })
    .fail(function() {
      console.log("error");
    })
    .always(function() {
      console.log("complete");
    });
})
//




});
</script>






<!-- 美洽代码 -->
<script type='text/javascript'>
  (function(m, ei, q, i, a, j, s) {
      m[i] = m[i] || function() {
          (m[i].a = m[i].a || []).push(arguments)
      };
      j = ei.createElement(q),
          s = ei.getElementsByTagName(q)[0];
      j.async = true;
      j.charset = 'UTF-8';
      j.src = '//static.meiqia.com/dist/meiqia.js';
      s.parentNode.insertBefore(j, s);
  })(window, document, 'script', '_MEIQIA');
  _MEIQIA('entId', 42733);
</script>
<script>
  // 你可以自己的代码中选择合适的时机来调用手动初始化
  _MEIQIA('init');
</script>
<!--  -->

app/views/common/_user_img.html.erb
<% if img_by(user).present? %>
  <!-- 用户头像 -->
  <%= image_tag img_by(user) %>  
<% else %>
  <!-- 更换了一个更快的150x150源 -->
  <%= image_tag "https://ooo.0o0.ooo/2016/11/16/582bf606808e2.png" %>  
<% end %>

app/views/common/_user_name.html.erb
<%= user.user_name%>

<%if !user.is_vip?%>
  <%= content_tag(:span,"", class:"fa fa-opera")%>
<%else%>
  <%= content_tag(:span,"", class:"fa fa-vimeo")%>
<%end%>